# Generated by Django 6.0.1 on 2026-02-06 01:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('churn_analysis', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChurnAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_file', models.FileField(blank=True, null=True, upload_to='uploads/input/')),
                ('output_file', models.FileField(upload_to='uploads/output/')),
                ('filename', models.CharField(max_length=255)),
                ('churn_rate', models.FloatField()),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('has_churn_column', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='churn_analyses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='UploadedFile',
        ),
    ]
